const app = (id, title, kind, description, href, status, category = "tool", extra = {}) => ({
  id,
  title,
  kind,
  description,
  href,
  status,
  category,
  ...extra,
});

export const HUB_AREAS = [
  {
    id: "growth",
    missionId: "growth",
    name: "Growth",
    short: "GR",
    leader: "Andrei",
    color: "#A78BFA",
    position: "xl:col-span-2",
    description: "Demanda, aquisicao, funis, conversao e experimentos que conectam as areas.",
    objective: "Transformar canais e produtos em crescimento mensuravel.",
    objectives: [
      { title: "Gerar demanda qualificada", krs: [{ id: "growth-creator-leads", label: "Leads para Aquisicao", target: "25.000" }, { id: "growth-brand-leads", label: "Leads para Vendas", target: "1.050" }] },
      { title: "Novo produto com creators grandes", krs: [{ id: "growth-creator-contract", label: "Contrato fechado", target: "1" }, { id: "growth-product-funnel", label: "Funil operando", target: "100%" }, { id: "growth-product-sales", label: "Vendas", target: "30" }] },
    ],
    pendingKpis: ["Leads pagos", "Investimento", "CPL"],
    apps: [
      app("growth-central", "Growth Central", "Dashboard executivo", "Plano, prioridades, canais e indicadores de Growth.", "/hub/growth", "operacional"),
      app("growth-funis", "Funis de Creators e Marcas", "Funis", "Leitura separada por publico, canal e etapa.", "/hub/funis", "operacional"),
      app("growth-cac-ltv", "Creator CAC x LTV", "Economia de creator", "Aquisicao, GMV, receita, CAC e retencao por creator.", "/hub/creator-economics", "operacional"),
      app("growth-novo-funil", "Novo Funil de Marcas", "Projeto", "Jornada, estrategia, criativos e implementacao do novo funil.", "https://lp.amplifyugc.co/projeto-novo-funil-marcas/", "integracao", "link"),
      app("growth-lp-curso", "LP Curso TikTok Shop", "Landing page", "Pagina educacional para marcas sobre TikTok Shop e creators.", "https://lp.amplifyugc.co/aula-tiktok-shop/", "publicado", "link"),
      app("growth-central-lps", "Central de LPs", "Biblioteca", "Paginas de mentoria, curso e ofertas em uma entrada.", "https://lp.amplifyugc.co/central-lps/", "revisao", "link"),
    ],
  },
  {
    id: "marketing",
    missionId: "marketing",
    name: "MKT",
    short: "MK",
    leader: "Camila",
    color: "#FFD60A",
    position: "xl:col-span-2",
    description: "Midia, criativos, campanhas, ofertas e inteligencia para gerar demanda.",
    objective: "Aumentar alcance qualificado e transformar criativo em resultado.",
    objectives: [
      { title: "Crescer as redes", krs: [{ id: "marketing-instagram", label: "Instagram", target: "40 mil" }, { id: "marketing-tiktok", label: "TikTok", target: "50 mil" }] },
      { title: "Adquirir creators", krs: [{ id: "marketing-leads", label: "Leads", target: "4.000" }, { label: "Funil operando", target: "100%" }, { id: "marketing-podcast-recordings", label: "Gravacoes de podcast", target: "3" }] },
      { title: "Mansao Live Shop 2027", krs: [{ id: "marketing-mansion-instagram", label: "Seguidores", target: "2.500" }, { label: "Marca e plano", target: "Entregues" }] },
    ],
    pendingKpis: ["Alcance", "Seguidores", "Leads"],
    apps: [
      app("mkt-criativos-meta", "Dashboard de Criativos Meta", "Criativos", "Gasto, leads, CPL, Hook Rate, Hold Rate e decisao.", "https://amplify-creative-dashboard.netlify.app", "operacional"),
      app("mkt-meta-hub", "Meta Ads no Hub", "Midia paga", "Campanhas e criativos com leitura operacional.", "/meta", "operacional"),
      app("mkt-mapa-criativos", "Mapa de Criativos de Marcas", "Mapa estrategico", "Hooks, roteiros, referencias e ligacao com performance.", "/mapa-criativos-marcas", "operacional"),
      app("mkt-baw", "BAW TikTok Intelligence", "GMV Max", "Product e LIVE GMV Max, produtos, budget e gates.", "https://baw-tiktok-intelligence.netlify.app", "insumos"),
    ],
  },
  {
    id: "social-media",
    missionId: "social",
    name: "Social Media",
    short: "SM",
    leader: "Gean",
    color: "#64D2FF",
    position: "xl:col-span-2",
    description: "Conteudo, canais, autoridade, distribuicao e crescimento das redes.",
    objective: "Construir autoridade e transformar conteudo em demanda recorrente.",
    objectives: [
      { title: "Autoridade do Matheus e marcas", krs: [{ id: "social-instagram", label: "Instagram", target: "70 mil" }, { id: "social-youtube", label: "YouTube", target: "5 mil" }, { id: "social-tiktok", label: "TikTok", target: "5 mil" }] },
      { title: "Adquirir marcas", krs: [{ id: "social-brand-leads", label: "Leads", target: "450" }, { label: "Funil operando", target: "100%" }] },
      { title: "Crescer o podcast", krs: [{ id: "social-podcast-recordings", label: "Gravacoes", target: "6" }] },
    ],
    pendingKpis: ["Alcance", "Seguidores", "Conteudos"],
    apps: [
      app("social-mapa-criativos", "Mapa de Criativos", "Conteudo + performance", "Referencias, hooks e aprendizados de criativos de marcas.", "/mapa-criativos-marcas", "operacional"),
      app("social-dashboard-criativos", "Dashboard de Criativos", "Leitura de conteudo", "Sinais de atencao e conversao dos criativos em veiculacao.", "https://amplify-creative-dashboard.netlify.app", "operacional"),
      app("social-central-lps", "Central de LPs", "Destinos de conteudo", "Paginas usadas por conteudo, campanhas e ofertas.", "https://lp.amplifyugc.co/central-lps/", "revisao", "link"),
    ],
  },
  {
    id: "financeiro",
    missionId: "financeiro",
    name: "Financeiro",
    short: "FI",
    leader: "Nao definido",
    color: "#9CA3AF",
    position: "xl:col-start-2 xl:col-span-4",
    description: "Custos, margem e leituras financeiras disponiveis por produto ou programa.",
    objective: "Conectar receita, custo e margem sem misturar recortes de produtos.",
    objectives: [],
    pendingKpis: ["Receita", "Caixa", "Margem"],
    apps: [
      app("fin-custos", "Custos", "Dashboard financeiro", "Acompanhamento dos custos disponiveis no Hub.", "/custos", "operacional"),
      app("fin-metricas", "Metricas", "Indicadores", "Leitura consolidada dos indicadores disponiveis.", "/metricas", "operacional"),
      app("fin-margem", "Calculadora de Margem TikTok Shop", "Ferramenta", "Lucro, margem e ROAS minimo por canal.", "https://amplify-margem-shop.netlify.app", "publicado"),
      app("fin-super", "Super Afiliado", "Programa", "GMV e receita atribuivel ao programa.", "/superafiliado", "operacional"),
      app("fin-club", "Amplify Club", "Produto", "GMV e receita do Club como recorte proprio.", "/club", "operacional"),
    ],
  },
  {
    id: "aquisicao",
    missionId: "aquisicao",
    name: "Aquisicao",
    short: "AQ",
    leader: "Andrei",
    color: "#38BDF8",
    position: "xl:col-span-3",
    description: "Entrada, qualificacao, CRM, agenciamento e operacao do time de aquisicao.",
    objective: "Aumentar creators agenciados com rastreabilidade do primeiro contato ao aceite.",
    objectives: [
      { title: "Consolidar o Sniper", krs: [{ id: "aquisicao-sniper-gmv", label: "GMV dos creators adquiridos", target: "R$ 14 milhoes" }] },
      { title: "Crescer a base", krs: [{ id: "aquisicao-novos-creators", label: "Novos creators agenciados", target: "3.600 creators" }] },
    ],
    pendingKpis: ["Leads", "Agenciados", "Conversao"],
    apps: [
      app("aq-amplifyos", "AmplifyOS", "CRM novo · Vitor", "CRM e maquina nativa da nova operacao de aquisicao.", "https://amplifyos.up.railway.app", "operacional", "tool", { featured: true }),
      app("aq-cockpit", "Cockpit de Aquisicao", "Operacao do time", "Kanban, prazos, bloqueios e historico conectado ao Slack.", "https://amplify-mission-control.netlify.app/aquisicao", "operacional"),
      app("aq-dashboard", "Dashboard de Aquisicao", "Dashboard", "Leads, agenciados, conversao e origens.", "/analise", "operacional"),
      app("aq-cac-ltv", "Creator CAC x LTV", "Economia", "Aquisicao cruzada com GMV, receita e retencao.", "/hub/creator-economics", "operacional"),
      app("aq-funis", "Funis de Creators", "Funil", "Canais e conversoes da entrada ao agenciamento.", "/hub/funis", "operacional"),
    ],
  },
  {
    id: "vendas",
    missionId: "vendas",
    name: "Vendas",
    short: "VE",
    leader: "Luan",
    color: "#32D74B",
    position: "xl:col-span-3",
    description: "Pipeline comercial, propostas, reunioes, fechamento e expansao de receita.",
    objective: "Transformar demanda de marcas em receita e parcerias sustentaveis.",
    objectives: [
      { title: "Crescimento sustentavel", krs: [{ id: "vendas-revenue", label: "Faturamento no trimestre", target: "R$ 915 mil" }, { id: "vendas-cash", label: "Caixa no trimestre", target: "R$ 594.750" }] },
      { title: "Potencializar TAP", krs: [{ id: "vendas-tap", label: "Faturamento TAP", target: "R$ 1 milhao" }] },
      { title: "Mansao Live Shop 2027", krs: [{ id: "vendas-sponsor", label: "Cota de patrocinio", target: "1 cota" }, { label: "Reunioes", target: "50" }] },
    ],
    pendingKpis: ["Receita", "Caixa", "Pipeline"],
    apps: [
      app("vendas-funil", "Funil de Marcas", "Pipeline", "Leads e etapas comerciais de marcas sem misturar com creators.", "/hub/funis", "operacional"),
      app("vendas-proposta-laiz", "Proposta Comercial Laiz", "Proposta interativa", "Modelo visual para apresentar parceria e oferta.", "https://proposta-laiz-amplify.vercel.app", "publicado", "link"),
      app("vendas-margem", "Calculadora de Margem", "Ferramenta comercial", "Simulacao de margem e ROAS para TikTok Shop.", "https://amplify-margem-shop.netlify.app", "publicado"),
    ],
  },
  {
    id: "retencao",
    missionId: "retencao",
    name: "Retencao",
    short: "RE",
    leader: "Gabriel",
    color: "#FF9F0A",
    position: "xl:col-span-3",
    description: "Relacionamento, GMV, programas, gamificacoes e saude da base de creators.",
    objective: "Aumentar performance e permanencia dos creators na operacao.",
    objectives: [
      { title: "Aumentar a performance dos creators", krs: [{ id: "retencao-gmv-cap", label: "GMV CAP", target: "R$ 25 milhoes" }, { id: "retencao-gmv-tap", label: "GMV TAP", target: "R$ 1 milhao" }, { id: "retencao-creators", label: "Creators ativos", target: "4.000" }] },
    ],
    pendingKpis: ["Creators ativos", "GMV Total", "Receita Amplify"],
    preserveNotice: "Os sistemas desta area permanecem nos locais criados pelo Gabriel. O Hub apenas aponta para eles.",
    apps: [
      app("ret-club", "Amplify Club", "Dashboard", "GMV, categorias, elegibilidade e leitura recorrente.", "/club", "operacional"),
      app("ret-virada", "Virada do Club", "Fluxo", "Fechamento mensal com dry-run, fontes e historico.", "/hub/projetos", "operacional"),
      app("ret-indique", "Indique e Ganhe", "Programa", "Indicacoes, creators, conversao e resultado.", "/indiqueeganhe", "operacional"),
      app("ret-super", "Super Afiliado", "Programa", "Creators indicados, conversao, vendas e GMV.", "/superafiliado", "operacional"),
      app("ret-gamificacoes", "Gamificacoes", "Central operacional", "Acompanhamento das gamificacoes e atualizacoes.", "/gamificacoes", "operacional"),
      app("ret-base", "Base e Dashboard de Retencao", "Pipeline", "Snapshots e leituras operacionais preservados na estrutura atual.", "/hub/projetos", "operacional"),
    ],
  },
  {
    id: "projetos",
    missionId: "projetos",
    name: "Projetos",
    short: "PR",
    leader: "Emilly",
    color: "#FF375F",
    position: "xl:col-span-3",
    description: "Projetos, fluxos, entregas, controles e ferramentas internas da empresa.",
    objective: "Dar visibilidade ao que esta sendo construido, executado e entregue.",
    objectives: [
      { title: "Validar agencia TSP", krs: [{ id: "projetos-tsp-revenue", label: "Faturamento ate setembro", target: "R$ 100 mil" }] },
      { title: "Entregar com excelencia", krs: [{ id: "projetos-churn", label: "Churn do novo produto", target: "< 20%" }] },
      { title: "Aumentar upsell", krs: [{ id: "projetos-upsell", label: "Faturamento em upsell", target: "R$ 80 mil" }] },
      { title: "Validar SuperLive", krs: [{ id: "projetos-superlive-revenue", label: "GMV em uma Super Live", target: "R$ 250 mil" }, { id: "projetos-superlive-process", label: "Processo em operacao", target: "100%" }] },
    ],
    pendingKpis: ["Projetos no prazo", "Entregas", "Bloqueios"],
    apps: [
      app("proj-fluxos", "Projetos e Fluxos", "Central operacional", "Canvas, runs, fontes, guardrails e execucoes recorrentes.", "/hub/projetos", "operacional", "tool", { featured: true }),
      app("proj-mission-control", "Mission Control da Amplify", "Sistema executivo", "KRs, operacao, agentes e cockpit da empresa.", "https://amplify-mission-control.netlify.app", "operacional"),
      app("proj-hoje", "Hoje", "Visao operacional", "Entrada para a leitura diaria da operacao.", "/", "operacional"),
      app("proj-metricas", "Metricas", "Dashboard", "Metas e indicadores disponiveis no Hub.", "/metricas", "operacional"),
    ],
  },
];

export const HUB_AREA_MAP = Object.fromEntries(HUB_AREAS.map((area) => [area.id, area]));

export function catalogApps() {
  return HUB_AREAS.flatMap((area) => area.apps.map((item) => ({ ...item, sourceAreaId: area.id, sourceAreaName: area.name, sourceColor: area.color })));
}
